# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ps.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Fedavg.proto import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ps.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08ps.proto\x1a\x0c\x63ommon.proto\"3\n\x13Res_Pull_Dictionary\x12\x1c\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\r.ArrayRequest\"C\n\x13Req_Push_Dictionary\x12\x1c\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\r.ArrayRequest\x12\x0e\n\x06\x61\x63\x63_no\x18\x02 \x01(\x05\"\x13\n\x11ParameterPushResp\" \n\x10ParameterPullReq\x12\x0c\n\x04name\x18\x01 \x01(\t2\xb2\x01\n\x10ParameterService\x12\x37\n\x13VariableWeightsInit\x12\x0e.ResDictionary\x1a\x0e.ResDictionary\"\x00\x12\x32\n\x04Push\x12\x14.Req_Push_Dictionary\x1a\x12.ParameterPushResp\"\x00\x12\x31\n\x04Pull\x12\x11.ParameterPullReq\x1a\x14.Res_Pull_Dictionary\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_RES_PULL_DICTIONARY = _descriptor.Descriptor(
  name='Res_Pull_Dictionary',
  full_name='Res_Pull_Dictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='Res_Pull_Dictionary.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=77,
)


_REQ_PUSH_DICTIONARY = _descriptor.Descriptor(
  name='Req_Push_Dictionary',
  full_name='Req_Push_Dictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='Req_Push_Dictionary.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acc_no', full_name='Req_Push_Dictionary.acc_no', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=146,
)


_PARAMETERPUSHRESP = _descriptor.Descriptor(
  name='ParameterPushResp',
  full_name='ParameterPushResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=167,
)


_PARAMETERPULLREQ = _descriptor.Descriptor(
  name='ParameterPullReq',
  full_name='ParameterPullReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ParameterPullReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=201,
)

_RES_PULL_DICTIONARY.fields_by_name['entry'].message_type = common__pb2._ARRAYREQUEST
_REQ_PUSH_DICTIONARY.fields_by_name['entry'].message_type = common__pb2._ARRAYREQUEST
DESCRIPTOR.message_types_by_name['Res_Pull_Dictionary'] = _RES_PULL_DICTIONARY
DESCRIPTOR.message_types_by_name['Req_Push_Dictionary'] = _REQ_PUSH_DICTIONARY
DESCRIPTOR.message_types_by_name['ParameterPushResp'] = _PARAMETERPUSHRESP
DESCRIPTOR.message_types_by_name['ParameterPullReq'] = _PARAMETERPULLREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Res_Pull_Dictionary = _reflection.GeneratedProtocolMessageType('Res_Pull_Dictionary', (_message.Message,), {
  'DESCRIPTOR' : _RES_PULL_DICTIONARY,
  '__module__' : 'ps_pb2'
  # @@protoc_insertion_point(class_scope:Res_Pull_Dictionary)
  })
_sym_db.RegisterMessage(Res_Pull_Dictionary)

Req_Push_Dictionary = _reflection.GeneratedProtocolMessageType('Req_Push_Dictionary', (_message.Message,), {
  'DESCRIPTOR' : _REQ_PUSH_DICTIONARY,
  '__module__' : 'ps_pb2'
  # @@protoc_insertion_point(class_scope:Req_Push_Dictionary)
  })
_sym_db.RegisterMessage(Req_Push_Dictionary)

ParameterPushResp = _reflection.GeneratedProtocolMessageType('ParameterPushResp', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERPUSHRESP,
  '__module__' : 'ps_pb2'
  # @@protoc_insertion_point(class_scope:ParameterPushResp)
  })
_sym_db.RegisterMessage(ParameterPushResp)

ParameterPullReq = _reflection.GeneratedProtocolMessageType('ParameterPullReq', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERPULLREQ,
  '__module__' : 'ps_pb2'
  # @@protoc_insertion_point(class_scope:ParameterPullReq)
  })
_sym_db.RegisterMessage(ParameterPullReq)



_PARAMETERSERVICE = _descriptor.ServiceDescriptor(
  name='ParameterService',
  full_name='ParameterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=204,
  serialized_end=382,
  methods=[
  _descriptor.MethodDescriptor(
    name='VariableWeightsInit',
    full_name='ParameterService.VariableWeightsInit',
    index=0,
    containing_service=None,
    input_type=common__pb2._RESDICTIONARY,
    output_type=common__pb2._RESDICTIONARY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Push',
    full_name='ParameterService.Push',
    index=1,
    containing_service=None,
    input_type=_REQ_PUSH_DICTIONARY,
    output_type=_PARAMETERPUSHRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Pull',
    full_name='ParameterService.Pull',
    index=2,
    containing_service=None,
    input_type=_PARAMETERPULLREQ,
    output_type=_RES_PULL_DICTIONARY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARAMETERSERVICE)

DESCRIPTOR.services_by_name['ParameterService'] = _PARAMETERSERVICE

# @@protoc_insertion_point(module_scope)
