# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63ommon.proto\"7\n\x0c\x41rrayRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05\x61rray\x18\x02 \x03(\x02\x12\x0b\n\x03\x64im\x18\x03 \x03(\x05\"=\n\rReqDictionary\x12\x1c\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\r.ArrayRequest\x12\x0e\n\x06\x61\x63\x63_no\x18\x02 \x01(\x05\"8\n\rArrayResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05\x61rray\x18\x02 \x03(\x02\x12\x0b\n\x03\x64im\x18\x03 \x03(\x05\".\n\rResDictionary\x12\x1d\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x0e.ArrayResponseb\x06proto3'
)




_ARRAYREQUEST = _descriptor.Descriptor(
  name='ArrayRequest',
  full_name='ArrayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ArrayRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='array', full_name='ArrayRequest.array', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dim', full_name='ArrayRequest.dim', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=71,
)


_REQDICTIONARY = _descriptor.Descriptor(
  name='ReqDictionary',
  full_name='ReqDictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='ReqDictionary.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acc_no', full_name='ReqDictionary.acc_no', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=134,
)


_ARRAYRESPONSE = _descriptor.Descriptor(
  name='ArrayResponse',
  full_name='ArrayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ArrayResponse.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='array', full_name='ArrayResponse.array', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dim', full_name='ArrayResponse.dim', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=192,
)


_RESDICTIONARY = _descriptor.Descriptor(
  name='ResDictionary',
  full_name='ResDictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='ResDictionary.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=240,
)

_REQDICTIONARY.fields_by_name['entry'].message_type = _ARRAYREQUEST
_RESDICTIONARY.fields_by_name['entry'].message_type = _ARRAYRESPONSE
DESCRIPTOR.message_types_by_name['ArrayRequest'] = _ARRAYREQUEST
DESCRIPTOR.message_types_by_name['ReqDictionary'] = _REQDICTIONARY
DESCRIPTOR.message_types_by_name['ArrayResponse'] = _ARRAYRESPONSE
DESCRIPTOR.message_types_by_name['ResDictionary'] = _RESDICTIONARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArrayRequest = _reflection.GeneratedProtocolMessageType('ArrayRequest', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYREQUEST,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:ArrayRequest)
  })
_sym_db.RegisterMessage(ArrayRequest)

ReqDictionary = _reflection.GeneratedProtocolMessageType('ReqDictionary', (_message.Message,), {
  'DESCRIPTOR' : _REQDICTIONARY,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:ReqDictionary)
  })
_sym_db.RegisterMessage(ReqDictionary)

ArrayResponse = _reflection.GeneratedProtocolMessageType('ArrayResponse', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYRESPONSE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:ArrayResponse)
  })
_sym_db.RegisterMessage(ArrayResponse)

ResDictionary = _reflection.GeneratedProtocolMessageType('ResDictionary', (_message.Message,), {
  'DESCRIPTOR' : _RESDICTIONARY,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:ResDictionary)
  })
_sym_db.RegisterMessage(ResDictionary)


# @@protoc_insertion_point(module_scope)
